version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "test/**"
    ignore:
      - dependency-name: "*"
        # Ignore patch updates
        update-types: ["version-update:semver-patch"]
