version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        # Ignore patch updates
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
