AllCops:
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "test/integration/diagnose/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/LineLength:
  Max: 100

Style/Lambda:
  EnforcedStyle: lambda

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - "**/spec/*.rb"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - Rakefile
