#!/bin/bash

set -eu

echo "$ npm install"
npm install "$@"

echo "Check installed packages"
installed_packages=$(npm list --long --parseable | cut -d ':' -f 2)
successfully_installed=true
for package_item in "$@"; do
  if echo "$package_item" | grep "@latest"; then
    # Don't perform check for `@latest`, because the installed version number
    # won't match
    continue
  fi

  if ! echo "$installed_packages" | grep "$package_item"; then
    successfully_installed=false
    echo "Failed to install: $package_item"
  fi
done

if ! $successfully_installed; then
  echo "Installed packages:"
  echo "$installed_packages"
  exit 1
fi
