#!/bin/bash

set -eu

package=$1
shift

if [ "$package" == "" ]; then
  echo "No package specified!"
  echo "Usage: install_test_example_packages <package dir> <dependencies>"
  echo "Example: install_test_example_packages koa koa@1.2.3"
  exit 1
fi

example_path="packages/$package/test/example"

if [ ! -d "$example_path" ]; then
  echo "No test example directory for package $package in $example_path"
  echo "Please check if the directory exists in the packages/ directory"
  exit 1
fi

echo "Navigate to test app directory"
cd "$example_path"

echo "$ npm install"
npm install "$@"

echo "Check installed packages"
installed_packages=$(npm list --long --parseable | cut -d ':' -f 2)
successfully_installed=true
for package_item in "$@"; do
  if echo "$package_item" | grep "@latest"; then
    # Don't perform check for `@latest`, because the installed version number
    # won't match
    continue
  fi

  if ! echo "$installed_packages" | grep "$package_item"; then
    successfully_installed=false
    echo "Failed to install: $package_item"
  fi
done

if ! $successfully_installed; then
  echo "Installed packages:"
  echo "$installed_packages"
  exit 1
fi
