#!/bin/bash

set -eu

PATH_PREFIX=$PWD

npm install

# Extension package
(cd packages/nodejs-ext && npm link)
# Core package
(cd packages/nodejs && npm link)
# Integration packages
(cd packages/apollo-server && npm link)
(cd packages/express && npm link)
(cd packages/koa && npm link)
(cd packages/nextjs && npm link)
